version: '3'
services:
    scrader_server:
      image: scrader_server
      ports:
        - "8000:8000"
      environment:
        - SERVICE_PORTS=8000
      networks:
        - web
      deploy:
        replicas: 2
        update_config:
          parallelism: 1
          delay: 10s
      volumes:
        - .:/code
      depends_on:
        - db
    db:
      image: mongo:3.0.2
      ports:
        - "8080:27017"
      volumes:
        - ./dbdata:/data/db
        - ./mongod.conf:/etc/mongod.conf
      networks:
        - web
      command: mongod --auth
    proxy:
      image: dockercloud/haproxy
      depends_on:
        - db
        - scrader_server
      environment:
        - BALANCE=roundrobin
        - BACKEND_PORT=8000
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 8090:80
      networks:
        - web
      deploy:
        placement:
          constraints: [node.role == manager]
networks:
  web:
    driver: overlay
